### DISCUSSION TITLE
How does templating for rotz work ?

### DISCUSSION THREAD

**Discussion by aniketgm** [volllly/rotz#327] [General]
I'm am aware about Jinja. So I believe handlebars is somewhat similar. But how does this work for multiple defaults. I mean, let's say, I want to setup my config as below:
```
windows:
  winget:
    installs: winget install {{ name }}
  scoop:
    installs: scoop install {{ name }}
```
Is this possible ?

--------------------------------
Also, from [here](https://volllly.github.io/rotz/docs/configuration/defaults), it says,
> These files contain defaults which are automatically used in sub directories for empty keys in the dot.yaml files.

And my config is like this:

![image](https://github.com/volllly/rotz/assets/14215698/359572da-7eb5-4a00-bdae-6cc9f8c15a64)

So, how to set the empty keys:
Like this ?
```
windows:
```
Or like this:
```
windows:
  installs:
```
Because both does not work for me.

**Comment by volllly** [comment]
Hey, you can not have multiple different install commands in the defaults.

you'll have to decide which of the two you'll want as the default.

you can setup your dotfiles directory like this:
```
├── defaults.yaml
├── some
│   └── dot.yaml
└── other
    └── dot.yaml
```

```yaml
# defaults.yaml
windows:
  installs: winget install {{ name }}
```

the `some/dot.yaml` file is empty and uses the winget install command from the defaults.

this file overwrites that and uses scoop.
```yaml
# other/dot.yaml
windows:
  installs: scoop install {{ name }}
```

**Comment by volllly** [comment]
Another option is to have two subfolders with different defaults.


```
├── winget
│   ├── defaults.yaml
│   └── some
│       └── dot.yaml
└── scoop
    ├── defaults.yaml
    └── other
        └── dot.yaml
```

```yaml
# winget/defaults.yaml
windows:
  installs: winget install {{ name }}
```

```yaml
# scoop/defaults.yaml
windows:
  installs: scoop install {{ name }}
```

the `winget/some/dot.yaml` file is empty and uses the winget install command from the defaults.

the `scoop/other/dot.yaml` file is empty and uses the scoop install command from the defaults.
