### DISCUSSION TITLE
Template variables scoped to dot.yaml

### DISCUSSION THREAD

**Discussion by LeFauxMatt** [volllly/rotz#376] [Ideas]
I'd like to be able to scope a template variable to a particular dot.yaml file
The usecase is as follows:

**config.yaml**
```yaml
variables:
  package: {{ name }}
```

**defaults.yaml**
```yaml
windows:
  installs: |
    winget install `
      --id {{ package }} `
      --exact `
      --source winget `
      --accept-source-agreements `
      --disable-interactivity `
      --silent `
      --accept-package-agreements `
      --force
linux:
  installs:
    cmd: nala install {{ package }}
    depends:
      - nala
darwin:
  installs:
    cmd: brew install {{ package }}
    depends:
      - brew
```

**code/dot.yaml**
```yaml
windows:
  variables:
    package: Microsoft.VisualStudioCode
```

So that rather than having to insert the entire command in dot.yaml, I can just update the variable.
