### DISCUSSION TITLE
Evaluate PowerShell expression to calculate link destination

### DISCUSSION THREAD

**Discussion by AdamYellen** [volllly/rotz#72] [Ideas]
Sometimes the link destination isn't a straight forward path. E.g.
`(Split-Path $PROFILE.CurrentUserCurrentHost)\powershell.config.json`

How does rotz compute the destination? From my experimenting it does accept `~` but it's not clear to me what else is possible.

Does it make sense to evaluate the destination string before the link operation?

**Comment by volllly** [comment]
Hey,

I'm not sure how well this would work with other shells.

My hope is that most needs like this will be met by the [available variables](https://volllly.github.io/rotz/docs/configuration/templating#variables) in the templating engine. I've added a lot more in the latest release.

If thats not enough I think a new templating function like `eval` would be powerfull. Something like this:

```yaml
windows:
  links: 
    powershell.config.json: {{ #if (eq os "windows") }}{{ eval '"$(Split-Path $PROFILE.CurrentUserCurrentHost)\powershell.config.json"' }}{{ /if }}
```

Maybe for convenience also some helper functions that simplity the `{{#if (eq os "windows")}}` part: 
```yaml
windows:
  links: 
    powershell.config.json: {{ #windows }}{{ eval '"$(Split-Path $PROFILE.CurrentUserCurrentHost)\powershell.config.json"' }}{{ /windows }}
```

**Reply by AdamYellen** [reply]
An eval function would be perfect.

Why is the "if windows" needed in your examples? Could the parser completely skip over the top-level platform sections that don't apply?

**Reply by volllly** [reply]
Hey,

the templates are rendered before the file is parsed ATM.

One reason for that is that its easier to implement like this.
An other is that templates have a more power this way.

E.g. you can construct dynamic keys which would not be possible when just rendering parsed values:
```yaml
links:
  {{ #each something }}
  - key: {{ this }}
  {{ /each }}
```

I've implemented the `eval` and `windows`, `linux`, `darwin` helpers in [v0.8.0](https://github.com/volllly/rotz/releases/tag/v0.8.0) 🎉
