### ISSUE TITLE
`directories` template does not work

### ISSUE THREAD

**Issue by kaptcha0** [volllly/rotz#349]
I was hoping to use rotz to sync up my dotfiles no matter what OS I'm on. I discovered the template syntax [here](https://volllly.github.io/rotz/docs/configuration/templating#variables) and tried it out as follows:

```yaml
links:
  config.toml: {{ directories.config }}/helix/config.toml
  languages.toml: {{ directories.config }}/helix/languages.toml
```

However, when running `rotz link` I get the following messages:

```nushell
  languages.toml -> /helix/languages.toml
  config.toml -> /helix/config.toml
```

It seems like rotz isn't finding the appropriate config directories as defined in the `directories` crate.
