### ISSUE TITLE
Fallback on link hard

### ISSUE THREAD

**Issue by jtsagata** [volllly/rotz#389]
I have
```
linux:
  links:
    config.toml: ~/.config/atuin/config.toml
    themes: ~/.config/atuin/themes
```

With `link-type hard` the 2nd failed.

Solution if `hard` fails, either
-  try  `symbolic` 
-  always use `symbolic` on Linux on directories.
-  make the directories and hard link all files to folders and subfolders (maybe that is bad idea)
